
networks:
  my-network:
    driver: bridge 

services:

  app:
    container_name: fullstack-taskflow-app
    networks:
      - my-network
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - ${PORT_BACKEND}:5000
    environment:
      - PORT_BACKEND=${PORT_BACKEND}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  db:
    container_name: postgres_db 
    networks: 
      - my-network
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"] 
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data: